# version: "3.9"
services:
  quokka-backend:
    image: tedwon/quokka-backend:latest
    container_name: "quokka-backend"
    environment:
      TZ: Australia/Brisbane
    ports:
      - "2402:2402"
      - "8543:8443"
    restart: always
  quokka-frontend:
    depends_on:
      - quokka-backend
    image: tedwon/quokka-frontend:latest
    container_name: "quokka-frontend"
    environment:
      TZ: Australia/Brisbane
    ports:
      - "3000:3000"
    restart: always