version: "3.9"
services:
  quokka-db:
    image: postgres:latest
    volumes:
      - /var/quokka_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: quokka
      POSTGRES_PASSWORD: quokka
      POSTGRES_DB: quokka_db
  quokka-backend:
    depends_on:
      - quokka-db
    image: tedwon/quokka-backend:latest
    ports:
      - "8080:8080"
    restart: always
  quokka-frontend:
    depends_on:
      - quokka-backend
    image: tedwon/quokka-frontend:latest
    ports:
      - "3000:3000"
    restart: always
